name: Build wheels

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-wheels:
    name: cibuildwheel (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.16.5

      - name: Build wheels
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-*
          CIBW_SKIP: pp*
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BEFORE_BUILD: pip install --upgrade pip wheel 'cmake<3.30' ninja numpy
          CIBW_TEST_REQUIRES: numpy
          CIBW_TEST_COMMAND: python -c "import numpy as np, pixmask; x = np.zeros((16,16,3), dtype='uint8'); pixmask.sanitize(x)"
          CIBW_ENVIRONMENT: PIXMASK_BUILD_PYTHON=ON
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: pixmask-${{ matrix.os }}-wheels
          path: wheelhouse/*.whl
